version: '3.8'

services:
  runtime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '8.0'
    environment:
      RUNTIME_SSH: true
      RUNTIME_USER: vanegmond
      RUNTIME_PASSWORD: indainda
      RUNTIME_GROUP: veg
    ports:
      - 9080:80
      - 9443:443
      - 9222:22
