#!/command/with-contenv bash
if [ ! -f /etc/ssl/web/ssl.key ]; then
    echo "🏃‍ An SSL key was not detected, so I'll generate a self-signed SSL certificate pair for you..."
    mkdir -p /etc/ssl/web/
    openssl req -x509 -subj "/C=US/ST=Wisconsin/L=Milwaukee/O=IT/CN=default.test" -nodes -newkey rsa:2048 -keyout /etc/ssl/web/ssl.key -out /etc/ssl/web/ssl.crt -days 365 2>/dev/null
fi
