#!/command/with-contenv bash

if [[ $RUNTIME_UID != 1000 || $RUNTIME_GID != 1000 ]]; then
    # Change the group ID
    groupmod -o -g "$RUNTIME_GID" app

    # Change the User ID
    usermod -o -u "$RUNTIME_UID" app

    # Make sure the home directory is updated with the proper UID & GID
    chown app:app $RUNTIME_WORKDIR
    chown -R app:app $RUNTIME_USERDIR
fi

echo "
-------------------------------------
Container Info
-------------------------------------
User ID:       $(id -u app)
Group ID:      $(id -g app)
User Home:     ${RUNTIME_USERDIR}
Document Root: ${RUNTIME_WORKDIR}/public
Powered By:    sitepilot.io
-------------------------------------
"
