name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0', '8.1' ]

    name: Runtime ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker buildx build --tag ghcr.io/sitepilot/runtime:${{ matrix.php }} --build-arg PHP_VERSION=${{ matrix.php }} --platform linux/amd64,linux/arm64 .

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Publish image
        run: docker push ghcr.io/sitepilot/runtime:${{ matrix.php }}
        if: github.ref == 'refs/heads/main'
