name: build

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
        server: [ 'nginx', 'openlitespeed' ]

    name: Runtime ${{ matrix.server }} - ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/sitepilot/runtime:${{ matrix.php }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            PHP_VERSION=${{ matrix.php }}
        if: matrix.server == 'nginx'

      - name: Build and push OpenLiteSpeed image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/sitepilot/runtime:ols-${{ matrix.php }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            IMAGE=${{ matrix.server }}
            PHP_VERSION=${{ matrix.php }}
        if: matrix.server == 'openlitespeed'
